# fly.toml app configuration file generated for ethersubs on 2023-05-16T23:58:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ethersubs"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

 [build]
 
 [deploy]
  release_command = "sh ./release.sh"
 
 [env]
  PORT = "8080"
  USERNAME = "postgres"
  PASSWORD = "EYYV2otmYoAgBdt"
  DATABASE = "ethersubs-db"
  HOST = "ethersubs-db.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"